# Generated by Django 2.2.4 on 2021-03-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
