# Generated by Django 2.2.4 on 2021-03-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_buddy_app', '0002_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='num_shares',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
