# Generated by Django 2.2.4 on 2021-03-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_buddy_app', '0002_auto_20210304_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='ask_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='market_price',
        ),
    ]
