# Generated by Django 2.2.4 on 2021-03-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_buddy_app', '0003_position_num_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='stock_buddy_app.User'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
